site_name: The Foundry Way
site_description: 'Defence Digital Foundry'
site_author: 'Defence Digital Foundry'

docs_dir: docs/
repo_name: 'defencedigital/the-foundry-way'
repo_url: 'https://github.com/defencedigital/the-foundry-way'

theme:
  name: material
  custom_dir: theme/
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
  favicon: 'assets/img/favicon.ico'

extra_css:
  - assets/styles/extra.css
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/js/hljs/highlight.pack.js
  - assets/js/extra.js
  - assets/js/cookie-functions.js
  - assets/js/cookie-banner.js
  - assets/js/cookie-page.js
  - assets/js/govuk-frontend-3.14.0.min.js

# Page tree
nav:
  - Home: 'index.md'
  - 'Comms, content and publishing': 'comms-content-and-publishing/index.md'
  - Technology:
      - 'technology/index.md'
      - Tools: 'technology/tools/index.md'
      - Techniques: 'technology/techniques/index.md'
      - Platforms: 'technology/platforms/index.md'
      - Frameworks: 'technology/frameworks/index.md'
      - 'Reliability Engineering': 'technology/reliability-engineering/index.md'
      - 'Service levels': 'technology/reliability-engineering/service-levels.md'
